# Generated by Django 3.2.3 on 2021-08-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20210813_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfiddetails',
            name='user',
        ),
        migrations.AddField(
            model_name='rfiddetails',
            name='userDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.userdetails'),
        ),
    ]
