# Generated by Django 3.2.3 on 2021-08-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20210813_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('rfidDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.rfiddetails')),
                ('userDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.userdetails')),
            ],
        ),
    ]
