# Generated by Django 3.2.3 on 2021-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entities',
            name='rfidDetails',
        ),
        migrations.RemoveField(
            model_name='entities',
            name='userDetails',
        ),
        migrations.AddField(
            model_name='entities',
            name='carNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='houseNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='rfid',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='vehicleClass',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
